eslint-community/eslint-plugin-n

lib/rules/no-unsupported-features/es-syntax.js, tests/lib/rules/no-unsupported-features/es-syntax.js
<sup>(This PR was moved from https://github.com/mysticatea/eslint-plugin-node/pull/256 as that repository is currently unmaintained.)</sup>
This attempts to resolve https://github.com/mysticatea/eslint-plugin-node/issues/250 by specifying the supported version for dynamic imports. Check the original PR for discussions I opened on the code around some of my changes.
* Extend `case.supported` to support explicit `Range` instances
* Update error string for `no-dynamic-import`
* Update tests to check around those constraints
=> Allow dynamic import for Node.js >=12.17 <13 || >=13.2

lib/rules/exports-style.js, tests/lib/rules/exports-style.js
This is https://github.com/mysticatea/eslint-plugin-node/pull/208 against your fork now that `eslint-plugin-node` is unmaintained and `eslint-plugin-n` is being used by `eslint-config-standard` 😇 
It got reviewed by the original author, who then disappeared before merging it.
=> Make most variants of module.exports = { ... } fixable

lib/rules/file-extension-in-import.js, tests/lib/rules/file-extension-in-import.js
Given this configuration:
```
{
"n/file-extension-in-import": ["error", "always"]
}
```
and `file1.ts`
```ts
import something from "./file2"
```
eslint will `fix` this with a `.ts` added to the import statement, which is invalid and breaks the compilation of typescript.
When a typescript file (`.ts` / `.cts` / `.mts` files, [`.cts` and `.mts` have been supported since TypeScript 4.5](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#new-file-extensions)) imports another typescript file, eslint will now use the proper matching file extension instead of the original referenced file extension.
This means that, for example, when a `.ts` file imports another `.ts` file, eslint will now suggest using a `.js` extension in the import statement.
As far as I can tell, this …
=> Add proper file extensions when importing a typescript file from a typescript file

lib/rules/file-extension-in-import.js, lib/util/check-existence.js, lib/util/is-typescript.js, lib/util/map-typescript-extension.js, tests/lib/rules/no-missing-import.js
Closes #23
Refactored typescript logic into utilities for reuse.
=> Fix no-missing-import for typescript

.gitignore, lib/util/map-typescript-extension.js, tests/lib/rules/file-extension-in-import.js
Closes #28 
Thanks @calebeby for the identification.  It was my fault for not supplying enough tests in the original PR #20.
@aladdin-add this should be released as an immediate hotfix/patch.  Thank you
=> default mapping of source .ts import of unspecified extension should be  .js

lib/rules/no-unsupported-features/es-syntax.js
First off, much appreciated for forking and landing #13.  I tested out this package but was still hitting issues around top level exports.  I was able to narrow it down and fix by adding supported version of 13.2.0 to modules.  As you can see [here](https://github.com/nodejs/node/pull/29866), this is when they removed the experimental flag.  [13.2.0 Changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V13.md#2019-11-21-version-1320-current-mylesborins). I tested this locally and no longer see the following error:
```sh
10:1  error  Import and export declarations are not supported yet  n/no-unsupported-features/es-syntax
```
=> Add support for modules

package.json
To avoid confusion, update `package.json` links to the new repository location.
=> Update package.json links to new repository location

lib/util/check-prefer-global.js, tests/lib/rules/prefer-global/buffer.js, tests/lib/rules/prefer-global/console.js, tests/lib/rules/prefer-global/process.js, tests/lib/rules/prefer-global/text-decoder.js, tests/lib/rules/prefer-global/text-encoder.js, tests/lib/rules/prefer-global/url-search-params.js, tests/lib/rules/prefer-global/url.js
Example problem:
```ts
/* "n/prefer-global/buffer": "error" */
require('buffer').Buffer; // <- error
require('node:buffer').Buffer; // <- no error
```
This PR will allow for every `prefer-global` rule to check their module's `node:` counterparts.
=> fix: consider node: prefix in prefer-global rules

.github/workflows/CI.yml
it also changes the default node to v18(active lts), and upgrade github actions to v3.
=> build: add node v19(ubuntu)

docs/rules/no-unsupported-features.md, package.json
First stable [v1.0.0](https://github.com/bmish/eslint-doc-generator/releases/tag/v1.0.0) release of [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator).
Originally added in:
* https://github.com/eslint-community/eslint-plugin-n/pull/61
=> chore: update eslint-doc-generator to v1.0.0

lib/rules/no-unsupported-features/es-syntax.js
- Modules is available from v12.17
- Refactored `>=12.17 <13` to `^12.17`, which is the same thing but more readable
=> fix: modules support range

lib/util/check-extraneous.js
You can import a package itself by self-referencing it with the package name, instead of needing to use relative paths.
=> Allow imports of self-referenced package

README.md, docs/rules/no-deprecated-api.md, docs/rules/no-unsupported-features/es-builtins.md, docs/rules/no-unsupported-features/es-syntax.md, docs/rules/no-unsupported-features/node-builtins.md, lib/util/get-configured-node-version.js, tests/lib/rules/no-unsupported-features/es-syntax.js
node.js < 13, v15 has been eol.
and node.js v14 will be eol in a few months.
refs: #42
TODO:
=> feat!: engines.node defaults to 16.0.0

README.md, lib/configs/recommended-module.js, lib/configs/recommended-script.js
according to node.green, Node.js 16.0.0 supports all ES2021 features.
refs: https://github.com/eslint-community/eslint-plugin-n/issues/42
=> feat!: update default `ecmaVersion` to 2021

.gitignore, lib/util/is-typescript.js, lib/util/map-typescript-extension.js, tests/lib/rules/file-extension-in-import.js, tests/lib/rules/no-missing-import.js
As a caption. 
When i try to import `tsx` file extension from file.
the `js` extension won't working
=> fix: missing import recognise tsx extension

lib/rules/no-deprecated-api.js, lib/rules/no-unsupported-features/node-builtins.js, lib/rules/prefer-promises/dns.js, lib/rules/prefer-promises/fs.js, lib/util/check-prefer-global.js, lib/util/check-unsupported-builtins.js, lib/util/enumerate-property-names.js, lib/util/extend-trackmap-with-node-prefix.js, lib/util/unprefix-node-colon.js, tests/lib/rules/no-deprecated-api.js, tests/lib/rules/no-unsupported-features/node-builtins.js, tests/lib/rules/prefer-promises/dns.js, tests/lib/rules/prefer-promises/fs.js
fixes #81, fixes #94 
This PR fixes the following rules:
- [no-deprecated-api](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-deprecated-api)
- [no-unsupported-features/node-builtins](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/no-unsupported-features/node-builtins.md)
- [prefer-promises/dns](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/prefer-promises/dns.md)
- [prefer-promises/fs](https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/prefer-promises/fs.md)
`prefer-global` has been fixed in #63.
I don't think `no-restricted-import` and `no-restricted-require` should be fixed. This is because some users want to distinguish between modules with and without `node:` prefixes.
=> fix: support `node:` prefix

docs/rules/no-missing-import.md, docs/rules/no-missing-require.md, lib/rules/no-missing-import.js, lib/rules/no-missing-require.js, lib/util/check-existence.js, lib/util/get-typescript-extension-map.js, lib/util/map-typescript-extension.js, package.json, tests/lib/rules/file-extension-in-import.js, tests/lib/rules/no-missing-import.js, tests/lib/rules/no-missing-require.js
Reference #108
This adds the ability to configure the ts<>js extension mapping.
This is configured using the following:
1. Check the rule configuration `typescriptExtensionMap`
2. ESLint [shared setting](http://eslint.org/docs/user-guide/configuring.html#adding-shared-settings) `node.typescriptExtensionMap`
3. Use `.ts` <=> `.js`, `.cts` <=> `.cjs`, `.mts` <=> `.mjs`, `.tsx` <=> `.js`
=> feat: add the ability to configure typescript to javascript file extension conversion

.eslint-doc-generatorrc.js, README.md, docs/rules/no-deprecated-api.md, docs/rules/no-exports-assign.md, docs/rules/no-extraneous-import.md, docs/rules/no-extraneous-require.md, docs/rules/no-missing-import.md, docs/rules/no-missing-require.md, docs/rules/no-process-exit.md, docs/rules/no-unpublished-bin.md, docs/rules/no-unpublished-import.md, docs/rules/no-unpublished-require.md, docs/rules/no-unsupported-features/es-builtins.md, docs/rules/no-unsupported-features/es-syntax.md, docs/rules/no-unsupported-features/node-builtins.md, docs/rules/process-exit-as-throw.md, docs/rules/shebang.md, lib/index.js
=> feat: add config `recommended` and `mixed-esm-and-cjs`

docs/rules/file-extension-in-import.md, docs/rules/no-missing-import.md, docs/rules/no-missing-require.md, lib/rules/no-missing-import.js, lib/rules/no-missing-require.js, lib/util/get-tsconfig.js, lib/util/get-typescript-extension-map.js, package.json, tests/fixtures/no-missing/ts-extends/base.tsconfig.json, tests/fixtures/no-missing/ts-extends/tsconfig.json, tests/fixtures/no-missing/ts-preserve/tsconfig.json, tests/fixtures/no-missing/ts-react/tsconfig.json, tests/lib/rules/no-missing-import.js, tests/lib/rules/no-missing-require.js
This adds the ability to automatically detect the correct ts file mappings from the `tsconfig.json`
=> feat: Allow for automatic ts mapping detection

.eslint-doc-generatorrc.js, docs/rules/file-extension-in-import.md, docs/rules/no-extraneous-import.md, docs/rules/no-extraneous-require.md, docs/rules/no-missing-import.md, docs/rules/no-missing-require.md, docs/rules/no-unpublished-bin.md, docs/rules/no-unpublished-import.md, docs/rules/no-unpublished-require.md, docs/rules/shebang.md, docs/shared-settings.md
This is the final part of #108. Previous parts: #114, #112.
Hopefully this is a better way to document shared options in this package 👀
=> docs: Create a shared settings document

package.json
@bcomnes and I maintain a fork of the `npm-run-all` package that's also one of the many mysticatea packages out there.
Here's a PR that moves this module to make use of that up to date fork.
=> chore: use maintained `npm-run-all` fork

.editorconfig
This adds an `.editorconfig` file as this is the most ubiquitous config file I could find
=> chore: Add a .editorconfig file

lib/util/get-npmignore.js, tests/fixtures/no-unpublished/issue99/bin.js, tests/fixtures/no-unpublished/issue99/package.json, tests/lib/rules/no-unpublished-require.js
This normalises paths in `package.json#files` before we check to see if the file will be published to npm.
Context can be found in https://github.com/eslint-community/eslint-plugin-n/issues/122#issuecomment-1737693426
=> fix: Normalise `package.json#files` before checking ignores and whitelist

lib/rules/no-sync.js, tests/lib/rules/no-sync.js
This resolves named imports, or destructured requires:
```js
import { readFileSync } from 'node:fs';
const file = readFileSync('/file/path');
```
```js
const { readFileSync } = require('node:fs');
const file = readFileSync('/file/path');
```
---
This is the counterpoint to #128 and Option 1 for #102 (the simple option).
=> feat: detect non-member expressions in n/no-sync

README.md
It should also be fixed in the repo's "About", but I don't have access to edit that.
=> Fix grammatically incorrect `Additional ESLint's rules`

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new-rule.yml
it's mainly modified from eslint's issue templates. the repro link was changed to eslint-online-playground. A big thanks to @ota-meshi!
=> docs: add issue templates

lib/rules/file-extension-in-import.js, lib/util/import-target.js, tests/lib/rules/file-extension-in-import.js
This is a slightly different approach to solve #21.
In this case we only try to add extensions to relative and absolute paths, with the detection of the moduleTypes done inside the `ImportTarget`
=> feat: Export the moduleType from ImportTarget

lib/rules/callback-return.js, lib/rules/exports-style.js, lib/rules/file-extension-in-import.js, lib/rules/global-require.js, lib/rules/handle-callback-err.js, lib/rules/no-deprecated-api.js, lib/rules/no-exports-assign.js, lib/rules/no-extraneous-import.js, lib/rules/no-extraneous-require.js, lib/rules/no-hide-core-modules.js, lib/rules/no-missing-import.js, lib/rules/no-missing-require.js, lib/rules/no-path-concat.js, lib/rules/no-unpublished-bin.js, lib/rules/no-unpublished-import.js, lib/rules/no-unpublished-require.js, lib/rules/no-unsupported-features.js, lib/rules/no-unsupported-features/es-syntax.js, lib/rules/prefer-promises/dns.js, lib/rules/prefer-promises/fs.js, lib/rules/shebang.js, lib/util/check-prefer-global.js, lib/util/check-unsupported-builtins.js, lib/util/get-configured-node-version.js, lib/util/get-typescript-extension-map.js, lib/util/is-typescript.js, lib/util/visit-import.js, lib/util/visit-require.js, package.json
refs: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
fixes #143
=> feat: eslint v9.0.0 compatibility (fixes #143)

.eslint-doc-generatorrc.js, README.md, package.json
This [new feature](https://github.com/bmish/eslint-doc-generator/releases/tag/v1.5.0) ensures that all the configs are listed in the readme, with the same emojis as used in the rules list.
Config descriptions aren't defined inside the configs themselves pending this issue:
* https://github.com/bmish/eslint-doc-generator/issues/506
=> Auto-generate configs list with eslint-doc-generator

lib/rules/no-unsupported-features/es-syntax.js, tests/lib/rules/no-path-concat.js, tests/lib/rules/no-unsupported-features/es-syntax.js
refs: https://github.com/eslint-community/eslint-plugin-n/issues/34
the change was borrowed from https://github.com/mysticatea/eslint-plugin-node/pull/283
credits goes to @ota-meshi :)
=> feat: Add syntax check for ES2021 to no-unsupported-features/es-syntax rule

docs/rules/no-unsupported-features/es-builtins.md, lib/rules/no-unsupported-features/es-builtins.js, tests/lib/rules/no-unsupported-features/es-builtins.js
refs: https://github.com/eslint-community/eslint-plugin-n/issues/34
the change was borrowed from https://github.com/mysticatea/eslint-plugin-node/pull/284
credits goes to @ota-meshi. :)
=> feat: Add builtins check for ES2021 to no-unsupported-features/es-builtins rule

.github/workflows/CI.yml, lib/configs/recommended-module.js, lib/configs/recommended-script.js, lib/util/is-typescript.js
=> fix: eslint 7.0 support

.github/ISSUE_TEMPLATE/non-rule-change.yml
There is already an issue template for rule-related changes, but some changes do not apply to it. Therefore, this pull request adds a new one.
=> chore: add non-rule-change issue template

lib/rules/no-callback-literal.js, tests/lib/rules/no-callback-literal.js
=> fix: no-callback-literal ignore unknown nodes

README.md, docs/rules/prefer-node-protocol.md, lib/index.js, lib/rules/prefer-node-protocol.js, lib/util/strip-import-path-params.js, tests/lib/rules/prefer-node-protocol.js
closes: #77 
I tried porting the rules and tests of https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md.
=> Add n/prefer-node-protocol rule

docs/rules/file-extension-in-import.md
https://github.com/mysticatea/eslint-plugin-node/pull/325
=> docs: improve wording of file-extension-in-import docs

lib/unsupported-features/node-builtins-modules/events.js
Thank you @alex-kinokon for spotting this!
=> fix(no-unsupported-features): Remove use of `static` as a variable

lib/rules/shebang.js, tests/lib/rules/shebang.js
This is useful for passing arguments to node
=> feat(shebang): add support for env's split-string option

package.json
Fixes eslint-community/eslint-plugin-n#197 using the solution from eslint-community/eslint-utils#206
Only time that `^8.23.0 || >=9.0.0-0` may cause an issue is if we ship a stable version of `17.0.0` before ESLint ships a stable version of `9.0.0`.
We may want to keep `>=8.23.0` in our stable releases and only set it to `^8.23.0 || >=9.0.0-0` in our pre-releases.
=> fix: explicitly support ESLint 9.0.0 pre-releases

lib/rules/prefer-node-protocol.js, tests/lib/rules/prefer-node-protocol.js
Targets ignored completely when first not node built-in. Fixed it.
=> fix: prefer-node-protocol: not first target

lib/eslint-utils.d.ts, package.json
Fixes eslint-community/eslint-plugin-n#213
It finds and ignores 5 dependencies across 117 files: @typescript-eslint/typescript-estree, eslint, estree, json-schema, type-fest
=> chore: use `ts-ignore-import` to lighten the dependencies

lib/rules/prefer-node-protocol.js, lib/util/extend-trackmap-with-node-prefix.js, lib/util/import-target.js, lib/util/visit-import.js, lib/util/visit-require.js, package.json, tests/lib/rules/no-missing-require.js
Now we support node `>=18.18.0` we can remove `is-builtin-module` (https://github.com/sindresorhus/is-builtin-module/issues/12)
=> feat: remove "is-builtin-module" dependency (fixes #232)

lib/unsupported-features/node-builtins-modules/crypto.js, lib/unsupported-features/node-builtins-modules/http2.js, lib/unsupported-features/node-builtins-modules/process.js, lib/unsupported-features/node-builtins-modules/sea.js, lib/unsupported-features/node-builtins-modules/util.js, lib/unsupported-features/node-builtins-modules/vm.js, lib/unsupported-features/node-builtins.js
=> feat(no-unsupported-features): ✨ Update to node v20.12.0/v21.7.0

lib/util/check-unsupported-builtins.js, tests/lib/rules/no-unsupported-features/es-builtins.js
fixes https://github.com/eslint-community/eslint-plugin-n/issues/250
=> fix: unsupported-features/node-builtins-modules range compare

lib/rules/no-unsupported-features/node-builtins.js, lib/unsupported-features/node-builtins-modules/buffer.js, lib/unsupported-features/node-builtins-modules/stream.js, lib/unsupported-features/node-builtins.js, lib/unsupported-features/node-globals.js
This is my best effort to transcribe https://nodejs.org/api/globals.html into eslint-plugin-n format 😄
=> feat(node-builtins): Add node globals

lib/unsupported-features/node-builtins-modules/buffer.js, tests/lib/rules/no-unsupported-features/node-builtins.js
=> fix: Add supported version to Buffer constructor

docs/rules/no-unsupported-features/node-builtins.md, lib/rules/no-unsupported-features/node-builtins.js, lib/util/check-unsupported-builtins.js, tests/lib/rules/no-unsupported-features/node-builtins.js
=> feat: Add support for ignoring experemental features

README.md
=> docs: add maintainance info

docs/rules/no-deprecated-api.md, docs/rules/no-unsupported-features/node-builtins.md
=> docs(node-builtins): Specify that only static properties are supported

.github/ISSUE_TEMPLATE/bug-report.yml
The link to [playground](https://eslint-online-playground.netlify.app/) (in the template to [_Report a problem_](https://github.com/eslint-community/eslint-plugin-n/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml&title=Bug%3A+%28fill+in%29)) points to an example with only `eslint` and its flat configuration. I'm still using the legacy configuration, so I had trouble modifying the configuration to add `eslint-plugin-n`. I propose to provide a link to playground with a minimal configuration of `eslint` and `eslint-plugin-n`: https://eslint-online-playground.netlify.app/#eNptjzFuwzAMRa8icGqB2NndtbcoOxgybaiVSUGSgxSG717KUoAMWSiReJ//c4cU7ZXu4xo89T8JBrDCSbTxsryFKJZS6olv7x/IcAFK3nHuFZrdUgVuDRKzYTNHWQ02pAt+Wxx3jKBKZLqf1ETzuPlsvpCN2UsxppJpMLsuOS51GDdPZVQ7o3v5ytK1RJ0mQhiKW4wSESp2lE …
=> docs: Provide an example with eslint-plugin-n to Playground

docs/rules/hashbang.md, docs/rules/shebang.md, lib/rules/hashbang.js, tests/fixtures/shebang/object-bin/package.json, tests/lib/rules/hashbang.js
=> feat(hashbang): Add support to map extensions to executables

package.json, tests/lib/rules/no-missing-import.js
fixes #242
This simply adds a test to show that incorrectly configured exports don't get classed as "missing"
=> fix: Allow for misconfigured default exports

.github/workflows/release-please.yml
https://github.com/google-github-actions/release-please-action says:
> [DEPRECATED] Release Please Action - please use https://github.com/googleapis/release-please-action
=> Use up to date `googleapis/release-please-action` action name

docs/rules/no-unpublished-import.md, docs/rules/no-unpublished-require.md, lib/rules/no-unpublished-import.js, lib/rules/no-unpublished-require.js, lib/util/check-publish.js, tests/lib/rules/no-unpublished-import.js, tests/lib/rules/no-unpublished-require.js
This rule makes it possible to disable/enable the rule in private packages selectively.
Fixes #297 
Make https://github.com/eslint-community/eslint-plugin-n/pull/296 obsolete
=> feat: Add flag ignorePrivate to no-unpublished-x rules

package.json
Typescript 5.5:
Typescript 5.4:
=> fix: Revert ts version (5.5 -> 5.4)

lib/unsupported-features/node-builtins-modules/stream.js
=> fix: Duplex.from is supported in 16.8.0

docs/rules/process-exit-as-throw.md
The rule description could do with some work too, but for now this is an improvement and easy to do via the UI editor 😄
=> docs(process-exit-as-throw): update wording

lib/rules/prefer-node-protocol.js, tests/lib/rules/prefer-node-protocol.js
=> fix: Use our data set to work out if a module is a node module

docs/rules/no-extraneous-import.md, docs/rules/no-extraneous-require.md
I bumped into this today and the rule totally makes sense, but I think the docs are missing a slightly pedantic yet still important scenario regarding importing transitive dependencies.
=> docs: Explain the transitive dependency case for no-extraneous-*

lib/util/import-target.js, tests/fixtures/no-missing/issue-314/module/index.ts, tests/fixtures/no-missing/issue-314/tsconfig.json, tests/lib/rules/no-missing-import.js
This is a preliminary fix for #314
=> fix(no-missing-import): Resolve tsconfig paths relative to the tsconfig

lib/util/import-target.js, tests/fixtures/no-missing/issue-285/package.json, tests/lib/rules/no-missing-import.js
This covers over `enhanced-resolve`'s behaviour of throwing unresolved modules, as it cannot resolve builtin node modules.
This is done by adding a load of aliases that are effectivly: `{ name: moduleName, alias: false }` meaning that enhanced resolve does not throw.
=> fix(no-missing-import): Ignore node builtins in package.json `imports`

docs/rules/no-process-env.md, lib/rules/no-process-env.js, tests/lib/rules/no-process-env.js
This allows users to exclude specific variables from `no-process-env` using the `allowedVariables` string array.
=> feat(no-process-env): Allow users to exclude specific variables

docs/rules/no-missing-import.md, lib/rules/no-missing-import.js, tests/lib/rules/no-missing-import.js
Adds the ability to ignore type imports on `no-missing-import`
Closes #286
=> feat(no-missing-import): Add `ignoreTypeImport` options

lib/rules/no-deprecated-api.js
I've recently noticed that this module is starting to tag `process.nextTick()` as deprecated. But it's not. Essentially it's close to impossible to stop using for old code, because it will alter the order of callbacks being fired.
Here is the full discussion: https://github.com/nodejs/node/pull/51280. Note that Node.js still uses it _everywhere_, because it's not possible to replace it without breaking a lot of people.
=> fix(no-deprecated-api): dedeprecate `process.nextTick`

lib/unsupported-features/node-builtins-modules/module.js, lib/unsupported-features/node-builtins-modules/process.js, lib/unsupported-features/node-builtins-modules/worker_threads.js, lib/unsupported-features/node-globals.js
=> feat(no-unsupported): Support node 23.0.0 and 22.10.0

lib/unsupported-features/node-builtins-modules/process.js
=> fix(no-unsupported): support missing `process.features`

lib/unsupported-features/node-builtins-modules/util.js
Seems to be missed in #342, see #340
=> fix(no-unsupported): `getCallSite` is experimental

lib/unsupported-features/node-builtins-modules/test.js, lib/unsupported-features/node-builtins-modules/util.js
Supported:
- [`test.MockTimers`](https://nodejs.org/docs/v23.1.0/api/test.html#class-mocktimers)
- [`util.getSystemErrorMessage`](https://nodejs.org/docs/v23.1.0/api/util.html#utilgetsystemerrormessageerr)
=> feat(no-unsupported): Support node 23.1.0

lib/unsupported-features/node-builtins-modules/test.js
I've put the non-exported classes in here as well in case we would ever need them
Probably closes #377
---
Out of scope for this PR as the class isn't exported, but I was wondering how we would handle the "extends `node:stream`'s `Readable` class" in the case of `TestsStream` 🤔
`TestsStream` is only created in `16.19.0` & `18.9.0`, but `node:stream`'s `Readable` class is already existing way earlier.
For functionality that's present in `node:stream`'s `Readable` class before `16.19.0` & `18.9.0` we should just use `16.19.0` & `18.9.0` in `TestsStream` I think?
And for functionality that's added to `node:stream`'s `Readable` class after `16.19.0` & `18.9.0`, we just keep the same values I think?
Since I wasn't sure, I kept the original value as a comment
Unfortunately this means that we …
=> fix(no-unsupported): fix `node:test` module

lib/index.js
It's important that the exported plugin reference and the one used in the exported configs are the very same – else one will get an error like:
> ConfigError: Config "node/flat/recommended-module": Key "plugins": Cannot redefine plugin "n".
This since two plugins are only allowed to have the same key if they are `===` to one another. See: https://github.com/eslint/eslint/blob/0583c87c720afe0b9aef5367b1a0a77923eefe9d/lib/config/flat-config-schema.js#L373-L375
This caused a regression for me in https://github.com/voxpelli/eslint-config/blob/638bbad2580bc4246527a6f0d989dc8194547475/base-configs/node.js#L10
=> fix: exported / referenced plugin same instance

docs/rules/no-sync.md, lib/rules/no-sync.js, tests/lib/rules/no-sync.js
a successor of https://github.com/eslint-community/eslint-plugin-n/pull/364.
=> feat(no-sync): Add ignores option

lib/util/enumerate-property-names.js, tests/lib/rules/no-unsupported-features/node-builtins.js
Closes #395
This prevents the recusrion protection from blocking module alias publishing.
We look to have been missing 6 options from the ignores list :scream: 
|  | Valid `ignores` Count |
| --- | --- |
| Before | `1462` |
| After | `1468` |
=> fix(no-unsupported): Correctly handle recursive objects on a per module basis

lib/rules/no-unsupported-features/es-syntax.json
Hello, 
Promise.withResolvers is supported since node 22.11 but current config does not allow it.
[node.green](https://node.green/)
=> fix Promise.withResolvers is supported since node 22.11

lib/rules/prefer-node-protocol.js
Closes #404.
The main change is avoiding an expensive iteration with `ReferenceTracker.iterateGlobalReferences` by operating directly on ESLint's `CallExpression`s. I've used a similar approach for ESM imports/exports too rather than sticking with `"Program:exit"`.
Benchmarks and smoke tests were done in the [Svelte repository](https://github.com/sveltejs/svelte). Both reporting and `--fix`ing works as expected.
`master` branch:
```
Rule                                            | Time (ms) | Relative
:-----------------------------------------------|----------:|--------:
n/prefer-node-protocol                          |   902.571 |    51.8%
```
`prefer-node-protocol-performance` branch:
```
Rule                                            | Time (ms) | Relative …
```
=> perf: improve `prefer-node-protocol`'s performance

lib/util/import-target.js, tests/fixtures/no-extraneous/tsconfig-paths/index.ts, tests/fixtures/no-extraneous/tsconfig-paths/src/configurations/foo.ts, tests/fixtures/no-extraneous/tsconfig-paths/tsconfig.json, tests/lib/rules/no-extraneous-import.js
Closes #379 
I decided to be as minimalistic as possible in the changes (still, it fixes the problem) :)
The original solution proposed in the issue didn't work for me, because calculating `resolverConfig` depends on `moduleType`, but calculating the correct `moduleType` requires partially filling `resolverConfig` (in particular `resolverConfig.alias`), which would result in calling a separate method twice, which is obviously less performant, so I just inserted the necessary check into the `getModuleType` definition.
=> fix: False-positive `no-extraneous-import` when using the `tsconfig > paths` alias import

lib/eslint-utils.d.ts, lib/rules/no-unsupported-features/node-builtins.js, lib/unsupported-features/node-builtins.js, lib/unsupported-features/node-import-meta.js, lib/util/check-unsupported-builtins.js, package.json, tests/lib/rules/no-unsupported-features/node-builtins.js
This PR adds support for `import.meta` to the `no-unsupported-features/node-builtins` rule.
close #419
=> feat(node-builtin): Add support for import.meta properties

lib/util/get-allow-modules.js, tests/lib/rules/no-extraneous-import.js, tests/lib/rules/no-extraneous-require.js, tests/lib/rules/no-missing-import.js, tests/lib/rules/no-missing-require.js, tests/lib/rules/no-unpublished-import.js, tests/lib/rules/no-unpublished-require.js
**Update Module Name Pattern to Support Virtual Modules**
**Description**
• Modified the regular expression pattern in the schema definition to allow an optional "virtual:" prefix. This update enables the configuration to recognize virtual modules.
• The updated pattern now supports module identifiers that may start with "virtual:" followed by optionally scoped names and the module name (e.g., "virtual:@scope/module" or "virtual:module").
• Existing validation behavior is preserved for standard module names, ensuring backward compatibility.
• No changes were made to the core logic; only the schema pattern expression has been updated.
=> feat(allow-modules): include `virtual:` in the modules pattern

docs/rules/no-unpublished-import.md, lib/rules/no-unpublished-import.js, tests/fixtures/no-unpublished/4/package.json, tests/lib/rules/no-unpublished-import.js
I just found that the option `tryExtensions` is available in `no-unpublished-require`, but not in `no-unpublished-import`. So I add this option.
Both `lib/util/visit-require.js` and `lib/util/visit-import.js` support this option, so this PR should work.
Here is my manual test:
1. Create an empty project.
2. Create `package.json` at the project root with only one line `{"files":["index.mts","foo.mts"]}`.
3. Create `index.mts` at the project root with only one line `import foo from './foo'; import bar from './bar';`.
4. Install eslint and eslint-plugin-n by `npm i -D eslint eslint-plugin-n`.
5. Create `eslint.config.mjs` at the project root.
```js
import eslintPluginN from 'eslint-plugin-n'
export default [{
files: ['*.mts'],
plugins: { n: eslintPluginN },
// rules: { …
```
=> Allow to use `tryExtensions` in the rule `no-unpublished-import`

lib/unsupported-features/node-builtins-modules/https.js, lib/unsupported-features/node-builtins.js, tests/lib/rules/no-unsupported-features/node-builtins.js, tests/lib/rules/prefer-node-protocol.js, tests/lib/unsupported-features/node-builtins.js
=> fix: false negatives for `https` in `prefer-node-protocol`, and false negatives for `node:sqlite` in `node-builtins`

lib/rules/no-deprecated-api.js, lib/util/iterate-process-get-builtin-module-references.js, tests/lib/rules/no-deprecated-api.js
Part of https://github.com/eslint-community/eslint-plugin-n/issues/428
=> feat(no-deprecated-api): Add support for `process.getBuiltinModule()`

lib/rules/prefer-promises/dns.js, lib/rules/prefer-promises/fs.js, tests/lib/rules/prefer-promises/dns.js, tests/lib/rules/prefer-promises/fs.js
Part of https://github.com/eslint-community/eslint-plugin-n/issues/428
=> feat(prefer-promises): Add support for `process.getBuiltinModule()`

docs/rules/prefer-node-protocol.md, lib/rules/prefer-node-protocol.js, tests/lib/rules/prefer-node-protocol.js
=> feat(prefer-node-protocol): Add support for `process.getBuiltinModule()`

lib/util/check-unsupported-builtins.js, tests/lib/rules/no-unsupported-features/node-builtins.js
Part of https://github.com/eslint-community/eslint-plugin-n/issues/428
---
~~#432 needs to be merged first. This PR uses test cases from #432.~~
=> feat(node-builtins): Add support for `process.getBuiltinModule()`

lib/util/get-parser-services.js, package.json
- Remove `@typescript-eslint/utils`, which has `typescript` as a peer dependency.
Update the `getParserServices` function to handle parser services directly without relying on the removed utility.
- Warning received while installing `eslint-plugin-n` on JS projects without `typescript`:
```sh
warning "eslint-plugin-n > @typescript-eslint/utils@8.34.1" has unmet peer dependency "typescript@>=4.8.4 <5.9.0".
warning "eslint-plugin-n > ts-declaration-location@1.0.7" has unmet peer dependency "typescript@>=4.0.0".
warning "eslint-plugin-n > @typescript-eslint/utils > @typescript-eslint/typescript-estree@8.34.1" has unmet peer dependency "typescript@>=4.8.4 <5.9.0".
warning "eslint-plugin-n > @typescript-eslint/utils > @typescript-eslint/typescript-estree > …
```
=> chore(no-sync): remove `@typescript-eslint/utils`

lib/rules/no-path-concat.js, lib/util/eslint-compat.js, package.json
eslint@9.31.0 removed some of the RuleContext types (see eslint/eslint#19910), causing the `test:types` CI script to fail.
Since `eslint-plugin-n` still needs to support 8.x versions of `eslint`, the implementation that relies on `RuleContext`s can't be removed.
A simple solution to unblock the CI is to annotate the few places that rely on them with `@ts-ignore`.
When `eslint` 8.x support is dropped, these annotations should be removed. That, in turn, will expose the code that relies on `eslint` 8.x APIs, which should then also be removed.
As part of this PR, the `eslint` dependency was bumped to `^9.31.0`.
This was done in order to prevent developers from developing locally with older 9.x versions of `eslint` and accidentally introducing new code that relies on these types without …
=> fix(ci): Ignore type test failures for types present in ESLint 8 that we removed in ESLint 9.31.0

lib/util/get-convert-path.js, package.json
Follow up on #458 - as suggested in the PR discussion (see https://github.com/eslint-community/eslint-plugin-n/pull/458#issuecomment-3122682639), replace minimatch with globrex across the board, so we ship only one pattern matching dependency.
=> refactor: remove minimatch dependency

lib/util/import-target.js, tests/lib/rules/no-missing-import.js, tests/lib/rules/no-missing-require.js
Imported prefixed with `data:` are not modules to be resolved, but the direct data that should be imported (e.g., JavaScript code, JSON or WASM).
This PR adds support for such imports in the no-missing-import rule.
Note:
With this change, the rule doesn't attempt to parse the data being imported, it merely does not try to resolve it to a path (which would fail), and thus allows those imports in the user's code.
Fixes #464
=> fix(no-missing-import): Support data imports

package.json
Bump the `markdowncli-lint` version to the newest available version to solve the runtime deprecation warning about `f.R_OK`.
Fixes #467
=> fix(ci): bump markdowncli-lint version

lib/unsupported-features/node-builtins-modules/url.js
Closes #470 
`URL.createObjectURL`, `URL.revokeObjectURL` are stable from node `>= 22.17.0` (ref [PR](https://github.com/nodejs/node/pull/57513))
=> fix(no-unsupported): `URL.createObjectURL`, `URL.revokeObjectURL` are supported

lib/unsupported-features/node-builtins-modules/tls.js, tests/lib/rules/no-unsupported-features/node-builtins.js
`tls.DEFAULT_CIPHERS` has been available since Node.js 0.11.3. This configuration has a faulty listing that was copied verbatim from a faulty listing in the Node.js documentation.
See https://github.com/nodejs/node/issues/59246 for additional details.
Fixes #483
=> fix(node-builtins-modules/tls.js): Update minimal version
