lib/rules/no-unsupported-features/es-syntax.js
tests/lib/rules/no-unsupported-features/es-syntax.js

fix: range matching fails

---

lib/rules/no-unsupported-features/node-builtins.js

Please review and merge to upstream.

Add support report verion

---

docs/rules/no-unsupported-features/es-builtins.md
docs/rules/no-unsupported-features/es-syntax.md
docs/rules/no-unsupported-features/node-builtins.md
lib/rules/no-deprecated-api.js
lib/rules/no-unsupported-features/es-builtins.js
lib/rules/no-unsupported-features/es-syntax.js
lib/rules/no-unsupported-features/node-builtins.js
lib/util/check-unsupported-builtins.js
lib/util/get-configured-node-version.js
tests/lib/rules/no-deprecated-api.js
tests/lib/rules/no-unsupported-features/es-builtins.js
tests/lib/rules/no-unsupported-features/es-syntax.js
tests/lib/rules/no-unsupported-features/node-builtins.js

closes https://github.com/eslint-community/eslint-plugin-n/issues/46

feat: add version as a setting

---

.gitignore
lib/converted-esm/import-meta-resolve.js
lib/rules/no-hide-core-modules.js
lib/util/import-target.js
package.json
scripts/convert-pure-esm-to-cjs.js

Reverts eslint-community/eslint-plugin-n#87

Revert "Updated `import-meta-resolve` & pack it automatically"

---

docs/rules/no-callback-literal.md

docs: Fix spelling in no-callback-literal.md

---

.github/workflows/CI.yml
lib/util/import-target.js
package.json

fix: Change to using is-builtin-module

---

.prettierrc
package.json

refs: https://prettier.io/blog/2023/07/05/3.0.0.html

chore: upgrade prettier v3

---

.github/workflows/CI.yml
lib/configs/recommended-module.js
lib/configs/recommended-script.js
package.json

refs: https://github.com/eslint/eslint/pull/18252

feat: add `name` to flat configs

---

lib/rules/no-missing-import.js
tests/lib/rules/no-missing-import.js

feat(no-missing-imports): add `tryExtensions` option

---

lib/unsupported-features/node-builtins-modules/url.js

fix(unsupported-features): Improve URL module

---

lib/rules/no-unsupported-features/es-syntax.json

I think this is what we need to do for #248

feat: More es-syntax deprecations

---

lib/util/check-unsupported-builtins.js
tests/lib/rules/no-unsupported-features/es-builtins.js
tests/lib/rules/no-unsupported-features/node-builtins.js

fixes https://github.com/eslint-community/eslint-plugin-n/issues/250

fix: unsupported-features/node-builtins-modules

---

tests/lib/rules/no-missing-import.js

refs: https://github.com/eslint-community/eslint-plugin-n/issues/86

test: add a test for self-ref

---

lib/unsupported-features/node-builtins-modules/zlib.js

https://github.com/nodejs/node/pull/52692

feat(node-builtin): Add node 22.2.0 support

---

lib/unsupported-features/node-globals.js

feat: Update to node v22.4.0

---

lib/rules/no-deprecated-api.js
lib/unsupported-features/node-builtins-modules/inspector.js
lib/unsupported-features/node-builtins-modules/module.js
lib/unsupported-features/node-builtins-modules/path.js
lib/unsupported-features/node-builtins-modules/perf_hooks.js
lib/unsupported-features/node-builtins-modules/repl.js
lib/unsupported-features/node-builtins-modules/stream.js
lib/unsupported-features/node-builtins-modules/util.js
lib/unsupported-features/node-builtins-modules/zlib.js
lib/unsupported-features/node-builtins.js

The usual updates to no-unsupported :)

feat: Update no-unsupported to node v22.9.0

---

lib/unsupported-features/node-builtins-modules/inspector.js
lib/unsupported-features/node-builtins-modules/perf_hooks.js
lib/unsupported-features/node-builtins-modules/test.js
lib/unsupported-features/node-globals.js

feat(no-unsupported): support Node 20.18.0

---

lib/util/check-extraneous.js
lib/util/import-target.js
tests/fixtures/no-unpublished/tsconfig-paths-wildcard/.npmignore
tests/fixtures/no-unpublished/tsconfig-paths-wildcard/index.ts
tests/fixtures/no-unpublished/tsconfig-paths-wildcard/node_modules/@test/dev/package.json
tests/fixtures/no-unpublished/tsconfig-paths-wildcard/package.json
tests/fixtures/no-unpublished/tsconfig-paths-wildcard/tsconfig.json
tests/lib/rules/no-unpublished-import.js

fix(no-unpublished): `allowModules` option was disabled when using TS alias

---

lib/util/check-prefer-global.js
lib/util/iterate-process-get-builtin-module-references.js
tests/lib/rules/prefer-global/buffer.js
tests/lib/rules/prefer-global/console.js
tests/lib/rules/prefer-global/process.js
tests/lib/rules/prefer-global/text-decoder.js
tests/lib/rules/prefer-global/text-encoder.js
tests/lib/rules/prefer-global/url-search-params.js
tests/lib/rules/prefer-global/url.js

Part of https://github.com/eslint-community/eslint-plugin-n/issues/428

feat(prefer-global): Add support for `process.getBuiltinModule()`

---

.github/workflows/CI.yml

ci(ci): replace node 23 with 24 in test matrix

---

lib/unsupported-features/node-builtins-modules/process.js
lib/unsupported-features/node-builtins-modules/worker_threads.js

[process.features.require_module](https://nodejs.org/docs/v20.19.3/api/process.html#processfeaturesrequire_module)
[worker.postMessageToThread](https://nodejs.org/docs/v20.19.3/api/worker_threads.html#workerpostmessagetothreadthreadid-value-transferlist-timeout)

feat: Add missing features from node 20.19.0
